export default () => {
    return [{
            id: "471754308",
            title: "Halcyon Days",
            year: "2019",
            rated: "PG-13",
            genre: ["Drama"],
            duration: "1h 35min",
            production: "Diamond Studios",
            director: "Anthony Mwanza, Joe Russo",
            writer: "Christopher Chungu",
            cast: [
                "Bradley Cooper",
                "Brie Larson",
                "Chris Hemsworth",
                "Chris Evans",
            ],
            plot: "After a series of devastating events, the village is in ruins but Catherine has strong hope for the future.",
            language: "English",
            country: "ZM",
            awards: "N/A",
            poster: "https://images.unsplash.com/photo-1505421031134-e57263cae630?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=728&q=80",
            ratings: [],
            type: "movie"
        },
        {
            id: "472493182",
            title: "My family and I",
            year: "2019",
            rated: "PG-13",
            genre: ["Musical", "Adventure", "Fantasy"],
            duration: "1h 35min",
            production: "Diamond Studios",
            director: "Anthony Mwanza, Joe Russo",
            writer: "Christopher Chungu",
            cast: [
                "Bradley Cooper",
                "Brie Larson",
                "Chris Hemsworth",
                "Chris Evans",
            ],
            plot: "After a series of devastating events, the village is in ruins but Catherine has strong hope for the future.",
            language: "English",
            country: "ZM",
            awards: "N/A",
            poster: "https://images.unsplash.com/photo-1482858390432-3604b4c9ee07?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80",
            ratings: [],
            type: "movie"
        },
        {
            id: "472496812",
            title: "The African Dream",
            year: "2019",
            rated: "PG-16",
            genre: ["Drama", "Romance"],
            duration: "1h 35min",
            production: "Diamond Studios",
            director: "Anthony Mwanza, Joe Russo",
            writer: "Christopher Chungu",
            cast: [
                "Bradley Cooper",
                "Brie Larson",
                "Chris Hemsworth",
                "Chris Evans",
            ],
            plot: "After a series of devastating events, the village is in ruins but Catherine has strong hope for the future.",
            language: "English",
            country: "ZM",
            awards: "N/A",
            poster: "https://images.unsplash.com/photo-1537470373161-1e5445834d3e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=370&q=80",
            ratings: [],
            type: "movie"
        },
        {
            id: "472498069",
            title: "Too Far Too Soon",
            year: "2019",
            rated: "PG-18",
            genre: ["Thriller", "Drama"],
            duration: "1h 35min",
            production: "Diamond Studios",
            director: "Anthony Mwanza, Joe Russo",
            writer: "Christopher Chungu",
            cast: [
                "Bradley Cooper",
                "Brie Larson",
                "Chris Hemsworth",
                "Chris Evans",
            ],
            plot: "After a series of devastating events, the village is in ruins but Catherine has strong hope for the future.",
            language: "English",
            country: "ZM",
            awards: "N/A",
            poster: "https://images.unsplash.com/photo-1514588243446-49b3aa895d43?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80",
            ratings: [],
            type: "movie"
        },
    ]
}